import json
from datetime import datetime

# 假设上面的JSON数据已经保存在变量data中
data = {"status_code": 0, "comments": [
    {"cid": "7538981165035406138", "text": "大古老师华虹半导体还能入吗，长期持有", "aweme_id": "7538929120571575612",
     "create_time": 1755305841, "digg_count": 1, "status": 1,
     "user": {"uid": "93352017739", "short_id": "363878357", "nickname": "规矩了勒",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/tos-cn-i-0813c001_0af52fea77994c8d94c0f0dae8f5b24c",
                               "url_list": [
                                   "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-i-0813c001_0af52fea77994c8d94c0f0dae8f5b24c.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "", "enterprise_verify_reason": "", "is_ad_fake": False, "profile_component_disabled": None,
              "region": "CN", "commerce_user_level": 0, "platform_sync_info": None, "secret": 1, "geofencing": None,
              "user_canceled": False, "status": 1, "follower_status": 0, "comment_setting": 0, "cover_url": None,
              "item_list": None, "new_story_cover": None, "is_star": False, "type_label": None, "ad_cover_url": None,
              "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAApvYzZfpIfxJYJnKD4i32tJbNjO_MaqDT7fklI8esKVA", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": None,
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": None, "text_extra": [], "label_text": "", "label_type": -1, "reply_comment_total": 3,
     "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0, "user_buried": False, "label_list": None,
     "is_hot": True, "text_music_info": None, "image_list": None, "is_note_comment": 0, "ip_label": "四川",
     "can_share": True, "item_comment_total": 338, "level": 1, "video_list": None,
     "sort_tags": "{\"top_list\":1,\"eco_level_8\":1,\"eco_level_3\":1}", "is_user_tend_to_reply": False,
     "content_type": 1, "is_folded": False, "enter_from": "others_homepage"},
    {"cid": "7539452845839500070", "text": "老师，内蒙华电准备从火电通过收购绿电进行转型，这个未来有没有预期？", "aweme_id": "7538929120571575612",
     "create_time": 1755415665, "digg_count": 0, "status": 1,
     "user": {"uid": "74993514677", "short_id": "380658204", "nickname": "博山电机水泵",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/tos-cn-i-0813c001_oAEePmABfAC6A2DWAhVZ41IgGF9aTWyAUNEEAl",
                               "url_list": [
                                   "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-i-0813c001_oAEePmABfAC6A2DWAhVZ41IgGF9aTWyAUNEEAl.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "", "enterprise_verify_reason": "", "is_ad_fake": False, "profile_component_disabled": None,
              "region": "CN", "commerce_user_level": 0, "platform_sync_info": None, "secret": 0, "geofencing": None,
              "user_canceled": False, "status": 1, "follower_status": 0, "comment_setting": 0, "cover_url": None,
              "item_list": None, "new_story_cover": None, "is_star": False, "type_label": None, "ad_cover_url": None,
              "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAAK2DCG8IikXi5vI6tz4cIore6KXqa0M-w1bPvNUlKhjU", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": None,
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": None, "text_extra": [], "label_text": "", "label_type": -1, "reply_comment_total": 0,
     "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0, "user_buried": False, "label_list": None,
     "is_hot": False, "text_music_info": None, "image_list": None, "is_note_comment": 0, "ip_label": "山东",
     "can_share": True, "item_comment_total": 338, "level": 1, "video_list": None,
     "sort_tags": "{\"eco_level_3\":1,\"eco_level_8\":1,\"cold_start\":1}", "is_user_tend_to_reply": False,
     "content_type": 1, "is_folded": False, "enter_from": "others_homepage", "can_create_item": True},
    {"cid": "7539000858513064761", "text": "我已两层仓国电电力，已经跌了快一个月了[捂脸]", "aweme_id": "7538929120571575612",
     "create_time": 1755310426, "digg_count": 17, "status": 1,
     "user": {"uid": "351458712633155", "short_id": "96264758505", "nickname": "涛涛",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/tos-cn-i-0813c001_oEAALaBkiAwUBhJEAeL6AC0Ao7UEIDAfg0MpIi",
                               "url_list": [
                                   "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-i-0813c001_oEAALaBkiAwUBhJEAeL6AC0Ao7UEIDAfg0MpIi.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "lvtaotao2006", "enterprise_verify_reason": "", "is_ad_fake": False,
              "profile_component_disabled": None, "region": "CN", "commerce_user_level": 0, "platform_sync_info": None,
              "secret": 0, "geofencing": None, "user_canceled": False, "status": 1, "follower_status": 0,
              "comment_setting": 0, "cover_url": None, "item_list": None, "new_story_cover": None, "is_star": False,
              "type_label": None, "ad_cover_url": None, "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAAO-KXaai9s2tXxT2ZVR_mzN2fqdR6FGEEklMfl5PZflc", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": [],
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": [{"cid": "7539001717040448316", "text": "我记得是4.1开始讲的国电，不涨就收利息。每年两次分红，股息率远大于存款利息，好过市场90%的公司。",
                        "aweme_id": "7538929120571575612", "create_time": 1755310625, "digg_count": 31, "status": 1,
                        "user": {"uid": "110788933537", "short_id": "1999709934", "nickname": "大古。", "avatar_thumb": {
                            "uri": "100x100/aweme-avatar/tos-cn-i-0813_d774a9d9357a49519b0241d3fa4a369a", "url_list": [
                                "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-i-0813_d774a9d9357a49519b0241d3fa4a369a.jpeg?from=2064092626"],
                            "width": 720, "height": 720}, "follow_status": 1, "is_block": False, "custom_verify": "",
                                 "unique_id": "", "enterprise_verify_reason": "", "is_ad_fake": False,
                                 "followers_detail": None, "region": "CN", "commerce_user_level": 0,
                                 "platform_sync_info": None, "secret": 0, "geofencing": None, "user_canceled": False,
                                 "status": 1, "follower_status": 0, "comment_setting": 0, "cover_url": None,
                                 "item_list": None, "new_story_cover": None, "is_star": False, "type_label": None,
                                 "ad_cover_url": None, "relative_users": None, "cha_list": None,
                                 "sec_uid": "MS4wLjABAAAAF0AgqNESj4erTf3m0T1R9HgqhdgU4fhUw1b9VPdw3Y4",
                                 "need_points": None, "homepage_bottom_toast": None, "can_set_geofencing": None,
                                 "white_cover_url": None, "user_tags": None, "ban_user_functions": None,
                                 "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True,
                                                   "can_show_comment": True}, "card_entries": None,
                                 "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
                                 "interest_tags": None, "link_item_list": None, "user_permissions": None,
                                 "offline_info_list": None, "is_blocking_v2": False, "is_blocked_v2": False,
                                 "close_friend_type": 0, "signature_extra": None, "personal_tag_list": None,
                                 "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
                                 "follower_list_secondary_information_struct": None, "endorsement_info_list": None,
                                 "text_extra": None, "contrail_list": None, "data_label_list": None,
                                 "not_seen_item_id_list_v2": None, "special_people_labels": None,
                                 "familiar_visitor_user": None, "avatar_schema_list": None, "profile_mob_params": None,
                                 "disable_image_comment_saved": 0, "verification_permission_ids": None,
                                 "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None,
                                 "creator_tag_list": None, "private_relation_list": None, "identity_labels": None,
                                 "profile_component_disabled": None}, "reply_id": "7539000858513064761",
                        "user_digged": 0, "reply_comment": None, "text_extra": [], "label_text": "作者", "label_type": 1,
                        "reply_to_reply_id": "0", "is_author_digged": False, "user_buried": False, "label_list": None,
                        "is_hot": False, "text_music_info": None, "image_list": None, "is_note_comment": 0,
                        "ip_label": "浙江", "can_share": True, "level": 2, "video_list": None, "content_type": 1,
                        "is_folded": False}], "text_extra": [], "label_text": "", "label_type": -1,
     "reply_comment_total": 19, "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0,
     "user_buried": False, "label_list": None, "is_hot": True, "text_music_info": None, "image_list": None,
     "is_note_comment": 0, "ip_label": "重庆", "can_share": True, "item_comment_total": 338, "level": 1,
     "video_list": None, "sort_tags": "{\"top_list\":1,\"author_reply\":1}", "is_user_tend_to_reply": False,
     "content_type": 1, "is_folded": False, "enter_from": "homepage_hot"},
    {"cid": "7538966737141367586", "text": "大古老师，您之前说的国电，是国电电力，还是国电南瑞，还是国电南自？求教", "aweme_id": "7538929120571575612",
     "create_time": 1755302487, "digg_count": 3, "status": 1,
     "user": {"uid": "531812172696359", "short_id": "3511234867", "nickname": "王磊医生",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/tos-cn-avt-0015_5b5e2fbcfe4a8eedbb2b5b62f070851a",
                               "url_list": [
                                   "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_5b5e2fbcfe4a8eedbb2b5b62f070851a.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "danbaizhi595", "enterprise_verify_reason": "", "is_ad_fake": False,
              "profile_component_disabled": None, "region": "CN", "commerce_user_level": 0, "platform_sync_info": None,
              "secret": 0, "geofencing": None, "user_canceled": False, "status": 1, "follower_status": 0,
              "comment_setting": 0, "cover_url": None, "item_list": None, "new_story_cover": None, "is_star": False,
              "type_label": None, "ad_cover_url": None, "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAAxz4dS2jPfw3WsqbAfCL5c_Kqlc6NVa7mHZs_DChug-0", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": None,
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": None, "text_extra": [], "label_text": "", "label_type": -1, "reply_comment_total": 13,
     "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0, "user_buried": False, "label_list": None,
     "is_hot": True, "text_music_info": None, "image_list": None, "is_note_comment": 0, "ip_label": "江苏",
     "can_share": True, "item_comment_total": 338, "level": 1, "video_list": None,
     "sort_tags": "{\"top_list\":1,\"eco_level_7\":1,\"eco_level_8\":1,\"eco_level_3\":1}",
     "is_user_tend_to_reply": False, "content_type": 1, "is_folded": False, "enter_from": "others_homepage"},
    {"cid": "7539429222629868345", "text": "虽然听不懂[捂脸][捂脸]，但不影响天天来看大古的视频[偷笑]", "aweme_id": "7538929120571575612",
     "create_time": 1755410164, "digg_count": 0, "status": 1,
     "user": {"uid": "106099454306", "short_id": "1702760782", "nickname": "芹沁",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/tos-cn-avt-0015_cd06b453279f4f5e8529a7a7016bbaa3",
                               "url_list": [
                                   "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_cd06b453279f4f5e8529a7a7016bbaa3.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "cqq1606", "enterprise_verify_reason": "", "is_ad_fake": False,
              "profile_component_disabled": None, "region": "CN", "commerce_user_level": 0, "platform_sync_info": None,
              "secret": 0, "geofencing": None, "user_canceled": False, "status": 1, "follower_status": 0,
              "comment_setting": 0, "cover_url": None, "item_list": None, "new_story_cover": None, "is_star": False,
              "type_label": None, "ad_cover_url": None, "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAAaHfC_h6BPzEqr8lhG1oXd4y8j8nXKs8mrdexSlMjzms", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": None,
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": None, "text_extra": [], "label_text": "", "label_type": -1, "reply_comment_total": 0,
     "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0, "user_buried": False, "label_list": None,
     "is_hot": False, "text_music_info": None, "image_list": None, "is_note_comment": 0, "ip_label": "湖南",
     "can_share": True, "item_comment_total": 338, "level": 1, "video_list": None,
     "sort_tags": "{\"cold_start\":1,\"eco_level_7\":1,\"eco_level_8\":1,\"eco_level_3\":1}",
     "is_user_tend_to_reply": False, "content_type": 1, "is_folded": False, "enter_from": "others_homepage"},
    {"cid": "7539098179670901564", "text": "老师，我买了科创50恒生科技，还有一只有色，还有一个证券，还有一个算力，我这个组合可以吗[比心][比心]",
     "aweme_id": "7538929120571575612", "create_time": 1755333085, "digg_count": 3, "status": 1,
     "user": {"uid": "64193402748", "short_id": "67610265", "nickname": "A0领域造型",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/tos-cn-avt-0015_d21f12d1dcbaef4f1fde9a4f6b9d22a1",
                               "url_list": [
                                   "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_d21f12d1dcbaef4f1fde9a4f6b9d22a1.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "", "enterprise_verify_reason": "", "is_ad_fake": False, "profile_component_disabled": None,
              "region": "CN", "commerce_user_level": 0, "platform_sync_info": None, "secret": 0, "geofencing": None,
              "user_canceled": False, "status": 1, "follower_status": 0, "comment_setting": 0, "cover_url": None,
              "item_list": None, "new_story_cover": None, "is_star": False, "type_label": None, "ad_cover_url": None,
              "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAAHXwX7LpNQjWbKHoMDgkqhOEiuEgka1Bv64FFssVhpUE", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": [],
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": None, "text_extra": [], "label_text": "", "label_type": -1, "reply_comment_total": 2,
     "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0, "user_buried": False, "label_list": None,
     "is_hot": True, "text_music_info": None, "image_list": None, "is_note_comment": 0, "ip_label": "河南",
     "can_share": True, "item_comment_total": 338, "level": 1, "video_list": None,
     "sort_tags": "{\"top_list\":1,\"eco_level_8\":1}", "is_user_tend_to_reply": False, "content_type": 1,
     "is_folded": False, "enter_from": "others_homepage"},
    {"cid": "7538933215857361721", "text": "早上好，难怪现在身边人好多投资电力", "aweme_id": "7538929120571575612",
     "create_time": 1755294685, "digg_count": 15, "status": 1,
     "user": {"uid": "64250770412", "short_id": "2294030036", "nickname": "风之子",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/tos-cn-i-0813c001_o0CECImqgAlGA1ef98b1JknCNArmADAjXAqzAs",
                               "url_list": [
                                   "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-i-0813c001_o0CECImqgAlGA1ef98b1JknCNArmADAjXAqzAs.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "dyzq78xux44h", "enterprise_verify_reason": "", "is_ad_fake": False,
              "profile_component_disabled": None, "region": "CN", "commerce_user_level": 0, "platform_sync_info": None,
              "secret": 1, "geofencing": None, "user_canceled": False, "status": 1, "follower_status": 0,
              "comment_setting": 0, "cover_url": None, "item_list": None, "new_story_cover": None, "is_star": False,
              "type_label": None, "ad_cover_url": None, "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAA_K49t5rKl13JnhNLZ8S_bZeaUBUMBMdlIxi_rxbMF1Y", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": None,
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": None, "text_extra": [], "label_text": "", "label_type": -1, "reply_comment_total": 11,
     "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0, "user_buried": False, "label_list": None,
     "is_hot": True, "text_music_info": None, "image_list": None, "is_note_comment": 0, "ip_label": "山西",
     "can_share": True, "item_comment_total": 338, "level": 1, "video_list": None, "sort_tags": "{\"top_list\":1}",
     "is_user_tend_to_reply": False, "content_type": 1, "is_folded": False, "enter_from": "homepage_hot"},
    {"cid": "7538949791335170842", "text": "坚定拿着新华到现在，越拿越有信心[坏笑]", "aweme_id": "7538929120571575612",
     "create_time": 1755298539, "digg_count": 5, "status": 1,
     "user": {"uid": "98567089458", "short_id": "944650551", "nickname": "C…",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/tos-cn-avt-0015_1da3f7efa3f11e2da6d97d72fc514f66",
                               "url_list": [
                                   "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-avt-0015_1da3f7efa3f11e2da6d97d72fc514f66.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "", "enterprise_verify_reason": "", "is_ad_fake": False, "profile_component_disabled": None,
              "region": "CN", "commerce_user_level": 0, "platform_sync_info": None, "secret": 0, "geofencing": None,
              "user_canceled": False, "status": 1, "follower_status": 0, "comment_setting": 0, "cover_url": None,
              "item_list": None, "new_story_cover": None, "is_star": False, "type_label": None, "ad_cover_url": None,
              "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAAFmttYcHbsVdtwlhrPEbyhRYADzigyJEYIP6SigUKdgM", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": None,
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": None, "text_extra": [], "label_text": "", "label_type": -1, "reply_comment_total": 9,
     "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0, "user_buried": False, "label_list": None,
     "is_hot": True, "text_music_info": None, "image_list": None, "is_note_comment": 0, "ip_label": "福建",
     "can_share": True, "item_comment_total": 338, "level": 1, "video_list": None, "sort_tags": "{\"top_list\":1}",
     "is_user_tend_to_reply": False, "content_type": 1, "is_folded": False, "enter_from": "homepage_hot"},
    {"cid": "7539016350761567035", "text": "大古老师好，两天前刷到了您，把您的大部分视频看了一遍，顿觉相见恨晚，很多标的都已经涨的很多了，有没有适合现在入场的标的呢[玫瑰]",
     "aweme_id": "7538929120571575612", "create_time": 1755314032, "digg_count": 2, "status": 1,
     "user": {"uid": "109218625516", "short_id": "1856666378", "nickname": "Johnhal",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/mosaic-legacy_30f5a000ac0f0112e0f52", "url_list": [
                  "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/mosaic-legacy_30f5a000ac0f0112e0f52.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "", "enterprise_verify_reason": "", "is_ad_fake": False, "profile_component_disabled": None,
              "region": "CN", "commerce_user_level": 0, "platform_sync_info": None, "secret": 0, "geofencing": None,
              "user_canceled": False, "status": 1, "follower_status": 0, "comment_setting": 0, "cover_url": None,
              "item_list": None, "new_story_cover": None, "is_star": False, "type_label": None, "ad_cover_url": None,
              "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAAnX3C_xLRyQ8aoxtAT0gye9EXeb1A3d4ZN-NFV-icUqY", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": None,
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": None, "text_extra": [], "label_text": "", "label_type": -1, "reply_comment_total": 2,
     "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0, "user_buried": False, "label_list": None,
     "is_hot": True, "text_music_info": None, "image_list": None, "is_note_comment": 0, "ip_label": "福建",
     "can_share": True, "item_comment_total": 338, "level": 1, "video_list": None,
     "sort_tags": "{\"eco_level_3\":1,\"top_list\":1,\"eco_level_7\":1,\"eco_level_8\":1}",
     "is_user_tend_to_reply": False, "content_type": 1, "is_folded": False, "enter_from": "homepage_hot"},
    {"cid": "7538994406986367744", "text": "受大古老师启发，华虹吃了十厘米[抱拳]", "aweme_id": "7538929120571575612",
     "create_time": 1755308928, "digg_count": 1, "status": 1,
     "user": {"uid": "100540227688", "short_id": "2263212947", "nickname": "旅途",
              "avatar_thumb": {"uri": "100x100/aweme-avatar/mosaic-legacy_26ef20005ede9f1ae9db4", "url_list": [
                  "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/mosaic-legacy_26ef20005ede9f1ae9db4.jpeg?from=2064092626"],
                               "width": 720, "height": 720}, "follow_status": 0, "is_block": False, "custom_verify": "",
              "unique_id": "lvtu80597", "enterprise_verify_reason": "", "is_ad_fake": False,
              "profile_component_disabled": None, "region": "CN", "commerce_user_level": 0, "platform_sync_info": None,
              "secret": 0, "geofencing": None, "user_canceled": False, "status": 1, "follower_status": 0,
              "comment_setting": 0, "cover_url": None, "item_list": None, "new_story_cover": None, "is_star": False,
              "type_label": None, "ad_cover_url": None, "relative_users": None, "cha_list": None,
              "sec_uid": "MS4wLjABAAAA36qENl1Bq_UTGX6M6McB01_XZ0f9YY2AQxmYMRMdwA8", "need_points": None,
              "homepage_bottom_toast": None, "can_set_geofencing": None, "white_cover_url": None, "user_tags": None,
              "ban_user_functions": None,
              "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True, "can_show_comment": True},
              "card_entries": None, "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
              "interest_tags": None, "link_item_list": None, "user_permissions": None, "offline_info_list": None,
              "is_blocking_v2": False, "is_blocked_v2": False, "close_friend_type": 0, "signature_extra": None,
              "personal_tag_list": None, "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
              "follower_list_secondary_information_struct": None, "endorsement_info_list": None, "text_extra": None,
              "contrail_list": None, "data_label_list": None, "not_seen_item_id_list_v2": None,
              "special_people_labels": None, "familiar_visitor_user": None, "avatar_schema_list": None,
              "profile_mob_params": None, "disable_image_comment_saved": 0, "verification_permission_ids": None,
              "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None, "creator_tag_list": None,
              "private_relation_list": None, "identity_labels": None}, "reply_id": "0", "user_digged": 0,
     "reply_comment": [{"cid": "7539000859313636153", "text": "一直不让你们追高。[捂脸]", "aweme_id": "7538929120571575612",
                        "create_time": 1755310425, "digg_count": 4, "status": 1,
                        "user": {"uid": "110788933537", "short_id": "1999709934", "nickname": "大古。", "avatar_thumb": {
                            "uri": "100x100/aweme-avatar/tos-cn-i-0813_d774a9d9357a49519b0241d3fa4a369a", "url_list": [
                                "https://p3-pc.douyinpic.com/aweme/100x100/aweme-avatar/tos-cn-i-0813_d774a9d9357a49519b0241d3fa4a369a.jpeg?from=2064092626"],
                            "width": 720, "height": 720}, "follow_status": 1, "is_block": False, "custom_verify": "",
                                 "unique_id": "", "enterprise_verify_reason": "", "is_ad_fake": False,
                                 "followers_detail": None, "region": "CN", "commerce_user_level": 0,
                                 "platform_sync_info": None, "secret": 0, "geofencing": None, "user_canceled": False,
                                 "status": 1, "follower_status": 0, "comment_setting": 0, "cover_url": None,
                                 "item_list": None, "new_story_cover": None, "is_star": False, "type_label": None,
                                 "ad_cover_url": None, "relative_users": None, "cha_list": None,
                                 "sec_uid": "MS4wLjABAAAAF0AgqNESj4erTf3m0T1R9HgqhdgU4fhUw1b9VPdw3Y4",
                                 "need_points": None, "homepage_bottom_toast": None, "can_set_geofencing": None,
                                 "white_cover_url": None, "user_tags": None, "ban_user_functions": None,
                                 "aweme_control": {"can_forward": True, "can_share": True, "can_comment": True,
                                                   "can_show_comment": True}, "card_entries": None,
                                 "display_info": None, "card_entries_not_display": None, "card_sort_priority": None,
                                 "interest_tags": None, "link_item_list": None, "user_permissions": None,
                                 "offline_info_list": None, "is_blocking_v2": False, "is_blocked_v2": False,
                                 "close_friend_type": 0, "signature_extra": None, "personal_tag_list": None,
                                 "cf_list": None, "im_role_ids": None, "not_seen_item_id_list": None,
                                 "follower_list_secondary_information_struct": None, "endorsement_info_list": None,
                                 "text_extra": None, "contrail_list": None, "data_label_list": None,
                                 "not_seen_item_id_list_v2": None, "special_people_labels": None,
                                 "familiar_visitor_user": None, "avatar_schema_list": None, "profile_mob_params": None,
                                 "disable_image_comment_saved": 0, "verification_permission_ids": None,
                                 "batch_unfollow_relation_desc": None, "batch_unfollow_contain_tabs": None,
                                 "creator_tag_list": None, "private_relation_list": None, "identity_labels": None,
                                 "profile_component_disabled": None}, "reply_id": "7538994406986367744",
                        "user_digged": 0, "reply_comment": None, "text_extra": [], "label_text": "作者", "label_type": 1,
                        "reply_to_reply_id": "0", "is_author_digged": False, "user_buried": False, "label_list": None,
                        "is_hot": False, "text_music_info": None, "image_list": None, "is_note_comment": 0,
                        "ip_label": "浙江", "can_share": True, "level": 2, "video_list": None, "content_type": 1,
                        "is_folded": False}], "text_extra": [], "label_text": "", "label_type": -1,
     "reply_comment_total": 2, "reply_to_reply_id": "0", "is_author_digged": False, "stick_position": 0,
     "user_buried": False, "label_list": None, "is_hot": True, "text_music_info": None, "image_list": None,
     "is_note_comment": 0, "ip_label": "山东", "can_share": True, "item_comment_total": 338, "level": 1,
     "video_list": None, "sort_tags": "{\"author_reply\":1,\"top_list\":1}", "is_user_tend_to_reply": False,
     "content_type": 1, "is_folded": False, "enter_from": "homepage_hot"}], "cursor": 10, "has_more": 1,
        "reply_style": 2, "total": 338, "extra": {"now": 1755418559000, "fatal_item_ids": None},
        "log_pb": {"impr_id": "20250817161558E20B8A842C7AD1C73541"}, "hotsoon_filtered_count": 0, "user_commented": 0,
        "fast_response_comment": {"constant_response_words": ["赞", "比心", "加油"],
                                  "timed_response_words": ["早上好", "下午好", "晚上好"]}, "comment_config": {},
        "general_comment_config": {}, "show_management_entry_point": 0,
        "comment_common_data": "MS4wLjAAAAAA7nSVEbUQleM3oh70P30hGay3N0V8qvD9gxuCG1vEhMkFEeIUgFIU8rR4fRdFfp39Fd-34QKxayuX9W6UDMlJWe6whEvaShX3dWlc-Wql-xnEb0FIm92hkmRRuDCFkbdfb2TwpCI123gU9BPh_fOPF_5UKV6dRg2dYVg1z1qd1RVjnp0A1Rrcqhzi8pI00ShaiYQecvHUTPoWVxrKoxqyx9wCvnLG2AjwUh8vhL5Fkh7pbPoJA6cHVGTGGSx21L_QXZGm_SpaMH8Li5nQdEgxh_8NB3Og71eRUZ32CNSnyJdAJxDBIpmeDmN34vn2wF1DzBBLLxMTJQlAl3CKQrhzCTdqEwy7b1PsIJujwi6AN70rcFR9wPEbnqZLIpY4FRx4Epb1ZAhTpSYTUF3WLT0BjyekH9fVlEI4wKRFFtZdojWL5Tv6-ABYcaVJci1kUd-0XnEfYIaMH4rIK87G1ZOzlwmBXX8MUeLeUog9xZ5dH1mIt0SorIgk3IyygBcOyBDnrbUycEVi9hkyYxDB3daQ74zhs9AnhV8DqyObtoXh4Ykl_R-He7CER-DFSFTx3ABA0HP9e1yQBCykEvDs6PGRvBwIghKDwE2oVYkLZbtl6GGUjUTtz_DXpJASCpxlG3fRwcWIOCbsmCUh9-br5YxdJ5JkXmPIowxxwxQm5zcjXPUX93ZbsOR9Do8CXIvY1uWyOPm_hUBBBZ_zyTYvwbO1QrHEGwnWd91Dg7NtYOgMED2K0YQgpILDBNREswppxW5EFvK56Nleim6AiEahi5JvdyuSVb4rNEaKLs3NCBXVhvuB2RewgPgbDS0Xrrfa0ievHCOwfMnhbX5FgdSbEERxMT77jbRPRzJcLiBbe2HxoEkLrB58LK-mXQHXhPMpws9lKbt53_o43Ln5RmghBzy40O2xuhVzXT3xf98fuznGmUHR3jTtYQB2-7qk-wmaEknhI0QOEQCU-LY-v-_BwFQ2cLC9Kb-BguDBeMpoStxXFLAi-2pHOAWBvD39u-AdQtKua6iLAfz5EIafCLYaxWvW8kOItE5sZN557F4NHdECvCarUXtc3lL08r_xs7n95SqwzkyvkrKMrHXaUH34HnjIhuIsC-b5f2y-TWFZEkrMnc2_sellpW5Qfw4u_BB9xQBw1DW4XZCLD3TyoFwCJAOoc49E2bVGAgV5WDIZxfe3EX39zwPL--Cdz74JIH_IWq5OwRLBZNeveoSjoZeQQokVwOnZZ50LnyAd5GEngg7h7PoC6vdu9HRKHJodrHM2E6bk_M7GjJuukNqCDSUwaRCW1eUqHnB1MBqBms28mRoHvfPyZ21uqCA1lTH4V4gIOQcD5udco2EXSuN6pS4ZYoEkeSm6w9tl1c8c5T-tff_3t4xBEPPXniU7lcGGw-5qwQsXyvy64FLx9lzKAY6AzHodYfJ0iADQrk15ZQVxnHe8TNNbBi4pRQe3aue34u76SderCA-J61yRMAzp-Ib3lhi2E4Idv82LAWL96CLNt68aAvHudywufRElV0Tg4UOvB_DJNQ2tkWFaRI27aI03gpcNKkmwPjGHmDQAZcUPcAHypsQKBLYk2-O03xfrQuNh5x6rUs8ltmX32GYn5U5dg3fyCJndj3u9IqSJ1WoKpkf00W1enjVqNhuVG7ETOEtjodPiOqNP_HUO6uwPqaSxyV1xHpEH9A6O0OS73dGmVQ7l7QTijuO7P6eO08tmVubAz9eLUzZonV3z7VgcYjSZU4dPc_kWlPdCQSRvak_5QlMNmbiV6dGgtkWR_UOffhEm-hHiG42L-GMlJd3PhuGvyvC31J-kEd_4zgKtRSN2_xQqrreqHrvHJ5QQy3WnvbiqHHbe90Q47qgwX1xFCiHr3Dt5Mq5xb5T-dxdR6Rt2ec-KF8RIqhntQm7v8Fm_gG8IXZQX0EY6f-Jz7dEGxJq1QBAGfWs_6rx_riyiR9qEj7FBymUvjfi7WyOACcwXBLiQxrIhaIBESp_QS2vgHlVG7eRFC2in1aKCDxl_EJLsOJHdjOjDDIS2OwnF0EQfqITws6qFz9IWPmTUUp3sN8C45C9QOxBwSTNx2eUapyYHR5qFy4mApoS-9ibtrGStBNlLesclum4hC7t75pcO6XKjsQ7rjqDJc_Y0dMC6MN6fSnn5g7p4HdEMUePPBi71h6nEasxLnK5shFJDNvOCMc8RaqAT7eSQJM2vVKw77mTSfYiIfnig6chPvnVLmK8nvHswttwDf7If4QtT05LuHHiCnqWQty9whc516O6d61R0Rj44b3z0ItDNrKfJSLxWyfpLI07bok1PuKiemZdY-unTrDsFI5jczoNEfXKrt6i_wCEn7dpggu9DHZvAPO-6gKdFWUZjWVD_PFelTZsh9sbkX0qh4zkJIpIwVT6ExYqC9odg_-PS_lvtcQXxe2CEnWlmBkXOkwvpwyjPG2_pTTQfPt01uWmxF2ROxgJAu7kdQK7oI9hBBUwK05kTumbfZIwfMIwLMmXU3N3oHYZHhcc6bDzwUf7oIbO7De4QX_pKMz5nmnfVFyenbGKESKSJMKbVqcTBc0oxUgBZ4aPcfqsjCfSVg7N50dzkOWN0Tr8wjsWg4vKJ_cZuab7OyFFddKQ5pf1Wwergdz6sgZ6_QhudPoTQ5von3PQPUvBKML05HXprOU3Rluz_KeWVTK7BtGdEwZbm6cRsFDHDSgC4pJvrlSkd6JMB9BeA3RehiP1z5Yu8ft6c_YvEDMbJ9EBKVLdwIMqyQmBRk390tQwI4dwHZCJaDZLFWLYC42ou3BIrX-6mwNdPn_ipLgjL8OFh9gltECbIizhxmfc6RAl4HwVHdaLTm2OmmnEgICmysdFq0t9ayjV4ZSYnC3rnL1QW9FNhPFOuQss3woICC1XfcTQXqN_CD5QP_tQjQ6anon-kNNsbUUOkFkRuFTpRftU8N3z5VfyH0my3uCqBmtKQ6trTuxvmCTVsepn0XDVNIfGF2Q3RIp6jD9UzYrSFx4Gfeud6aTaJ7ACq_jTd4K2YgeHfOunl5G452r_UNBybQBkgjK8RAbgVeM3HImTDC9_HQoNmVGa34qL1oZMJF0_8rKVIvRVB2pACdL5GlRJwFeEVqvAmhLM5hbmEe73ib3YGGv80jbXLR9QZFipTtqsgQRbBuCcG4fcQlwmSGUCwY7EL3bwFYMg",
        "folded_comment_count": 0}


def format_comments(comments, indent=0):
    # 按时间倒序排序评论
    sorted_comments = sorted(comments, key=lambda x: x['create_time'], reverse=True)

    for comment in sorted_comments:
        # 转换时间戳为可读格式
        create_time = datetime.fromtimestamp(comment['create_time']).strftime('%Y-%m-%d %H:%M:%S')

        # 打印评论信息
        print(' ' * indent + f"用户: {comment['user']['nickname']} ({comment['ip_label']})")
        print(' ' * indent + f"时间: {create_time}")
        print(' ' * indent + f"内容: {comment['text']}")
        print(' ' * indent + f"点赞数: {comment['digg_count']}")

        # 如果有回复评论，也按时间倒序排序
        if comment.get('reply_comment') and comment['reply_comment_total'] > 0:
            print(' ' * indent + "回复:")
            sorted_replies = sorted(comment['reply_comment'], key=lambda x: x['create_time'], reverse=True)
            for reply in sorted_replies:
                format_comments([reply], indent + 4)

        print(' ' * indent + "-" * 50)


# 提取并格式化评论
print("=" * 60)
print("视频评论分析（按时间倒序排列）")
print("=" * 60)
print(f"总评论数: {data['total']}")
print("=" * 60)

format_comments(data['comments'])
